image:
  repository: pcm32/galaxy-k8s
  tag: 20.05_7ddbf2
  pullPolicy: IfNotPresent

webHandlers:
  replicaCount: 1

jobHandlers:
  replicaCount: 1

resources:
  requests:
    cpu: 0.3
    memory: 1G
  limits:
    cpu: 1
    memory: 2G

persistence:
  storageClass: standard

influxdb:
  enabled: false

rabbitmq:
  enabled: true

postgresql:
  persistence:
    storageClass: standard
